In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ecommerce_sales_analytics_5000.csv", parse_dates= ["order_date"])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [4]:
df["payment_type"] = df["payment_method"].map({
    "Card":"Digital",
    "Wallet":"Digital",
    "COD":"Cash"
})

In [5]:
df["payment_type"].unique()

array(['Digital', 'Cash'], dtype=object)

In [9]:
df[["payment_method", "payment_type"]].head()

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [11]:
df.groupby("payment_type").size()

payment_type
Cash       1774
Digital    3226
dtype: int64

In [12]:
def revenue_category(row):
    if row["revenue"] > 500:
         return "High"
    elif row["revenue"] >= 200:
         return "medium"
    else:
         return "Low"

In [17]:
df["revenue_category"] = df.apply(revenue_category, axis = 1)

In [15]:
df["revenue_category"].head()

0      High
1    medium
2      High
3      High
4    medium
Name: revenue_category, dtype: object

In [18]:
df["revenue_category"].value_counts()

revenue_category
High      3252
medium    1098
Low        650
Name: count, dtype: int64

In [19]:
df[['revenue', 'revenue_category']]

      revenue revenue_category
0     1883.20             High
1      304.10           medium
2      644.35             High
3     2569.90             High
4      468.56           medium
...       ...              ...
4995   542.74             High
4996  1428.47             High
4997   176.06              Low
4998   437.38           medium
4999  1069.90             High

[5000 rows x 2 columns]

In [22]:
def add_profit(data):
    data['profit'] = data['revenue'] * 0.20
    return data

def add_net_revenue(data):
    data['net_revenue'] = data['revenue'] - data['profit']
    return data

df = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)
)

In [23]:
df[['revenue', 'profit', 'net_revenue']]

      revenue   profit  net_revenue
0     1883.20  376.640     1506.560
1      304.10   60.820      243.280
2      644.35  128.870      515.480
3     2569.90  513.980     2055.920
4      468.56   93.712      374.848
...       ...      ...          ...
4995   542.74  108.548      434.192
4996  1428.47  285.694     1142.776
4997   176.06   35.212      140.848
4998   437.38   87.476      349.904
4999  1069.90  213.980      855.920

[5000 rows x 3 columns]